In [5]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as pls


## Inicializando variables en Numpy

In [6]:
# Crea un objeto vector
vector_a = np.array([1, 3.1416, 40, 0, 2, 5])
print("vector a = \n{}".format(vector_a)) 

      # Crea una matriz
matriz_A = np.array([[1, 2], [3, 4], [5, 6]])
print("matriz A = \n{}".format(matriz_A)) 

vector a = 
[ 1.      3.1416 40.      0.      2.      5.    ]
matriz A = 
[[1 2]
 [3 4]
 [5 6]]


In [8]:
vr = np.array

Ejemplos de arreglos de numpy

In [9]:
vZ = np.zeros(5)
print("Un vector de ceros con 5 valores")
print(vZ)

Un vector de ceros con 5 valores
[0. 0. 0. 0. 0.]


In [10]:
mO = np.ones((3, 10))
print("Una matriz de 3 x 10 de puros unos")
print(mO)

Una matriz de 3 x 10 de puros unos
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [11]:
va = np.arange(10)
print("va = ")
print(va)

va = 
[0 1 2 3 4 5 6 7 8 9]


In [12]:
vb = np.arange(20,-10,-5)
print("vb = ")
print(vb)

vb = 
[20 15 10  5  0 -5]


In [13]:
print("Una matriz de ceros de las dimensiones de mO:")
print(np.zeros_like(mO))

Una matriz de ceros de las dimensiones de mO:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
mA = np.random.rand(5, 12)
print("Y una matriz con números aleatorios bajo una distribución uniforme entre 0 y 1")
print(mA)

Y una matriz con números aleatorios bajo una distribución uniforme entre 0 y 1
[[0.96994904 0.86672554 0.02381279 0.11325324 0.21769038 0.40559458
  0.73914287 0.6874913  0.96120528 0.00618759 0.27809095 0.16637125]
 [0.67814211 0.17483724 0.33516022 0.43668542 0.51154687 0.95067861
  0.14738114 0.02887549 0.85096212 0.82587958 0.58637697 0.12292254]
 [0.09026989 0.11196398 0.25411057 0.19516461 0.37032164 0.70130814
  0.76253376 0.36468289 0.78213152 0.78924122 0.18648652 0.76936403]
 [0.14988423 0.05610306 0.54700425 0.96196766 0.02555296 0.19964061
  0.83454818 0.8508567  0.10560862 0.34694229 0.44872919 0.27551151]
 [0.79019407 0.86340532 0.02648017 0.05681632 0.61202114 0.22904423
  0.52954639 0.23400702 0.64782299 0.73661164 0.16689643 0.09768887]]


## Ejercicio:
Crear las siguientes matrices:

Una matriz de 4 por 6 con valores aleatorios de acuerdo a una distribución normal con media cero y varianza unitaria.

Un vector de 10 elementos con valores aleatorios de números enteros entre 4 y 100

Una matriz diagonal de 5 por 5 cuyos elementos de la diagonal sean (1, 2, 3, 4, 5)

In [20]:
#1
mA = np.random.randn(4, 6)
print("Matriz 4x6 con valores aleatorios de acuerdo a una distribución normal con media cero y varianza unitaria:")
print(mA)

Matriz 4x6 con valores aleatorios de acuerdo a una distribución normal con media cero y varianza unitaria:
[[-0.47028152  0.89852208  1.7971383  -0.78190108 -1.8988178  -0.40731233]
 [ 0.92988749 -0.78011048 -0.98414137  0.10908305  0.63493246  2.06660379]
 [ 0.38525295  1.45013808 -1.20092611 -0.68911962 -0.56457639  0.31170098]
 [ 0.11339278 -0.01344339 -0.19455642  1.6891154   1.46581556 -0.41550964]]


In [23]:
import random

#2
mB = np.array([random.randint(4, 100) for x in range(10)])
print("Vector de 10 elementos con valores aleatorios de números enteros entre 4 y 100:")
print(mB)

Vector de 10 elementos con valores aleatorios de números enteros entre 4 y 100:
[ 6 41 27 77 47 53 32 50 21 97]


In [26]:
#3
mC = np.zeros((5,5))
for i in range(5):
    mC[i][i] = i+1
print("Una matriz diagonal de 5 por 5 cuyos elementos de la diagonal sean (1, 2, 3, 4, 5)")
print(mC)

Una matriz diagonal de 5 por 5 cuyos elementos de la diagonal sean (1, 2, 3, 4, 5)
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


## Operaciones básicas de los ndarray

In [27]:
# Vamos a generar varios ndarrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.random.rand(2, 3)

print("a = \n{}".format(a))
print("b = \n{}".format(b))

print("Suma de todos los números de b")
print(b.sum())

print("Media de cada columna de a")
print(a.mean(axis=0))

print("Transpuesta de a, forma larga")
print(a.transpose())

print("Transpuesta de a, forma preferida")
print(a.T)

print("10 * b = ")
print(10 * b)

print("a * b =")
print(a * b)

print("2 elevado a la matriz a")
print(np.power(2, a))

print("a elevada al cuadrado (elemento a elemento)")
print(np.power(a, 2))

print("a.dot(b.T) = ")
print(a.dot(b.T))

print("a.dot(b) debería dar error")
print(a.dot(b))

a = 
[[1 2 3]
 [4 5 6]]
b = 
[[0.13933037 0.41569291 0.76184839]
 [0.72926697 0.93404523 0.6112152 ]]
Suma de todos los números de b
3.591399079883961
Media de cada columna de a
[2.5 3.5 4.5]
Transpuesta de a, forma larga
[[1 4]
 [2 5]
 [3 6]]
Transpuesta de a, forma preferida
[[1 4]
 [2 5]
 [3 6]]
10 * b = 
[[1.39330374 4.15692907 7.61848394]
 [7.29266971 9.34045232 6.11215202]]
a * b =
[[0.13933037 0.83138581 2.28554518]
 [2.91706788 4.67022616 3.66729121]]
2 elevado a la matriz a
[[ 2  4  8]
 [16 32 64]]
a elevada al cuadrado (elemento a elemento)
[[ 1  4  9]
 [16 25 36]]
a.dot(b.T) = 
[[ 3.25626137  4.43100304]
 [ 7.2068764  11.25458525]]
a.dot(b) debería dar error


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

## Ejercicio:
Trata de inferir que es lo que debe contener cada array b, c, d, e, f, g, h sin hacer ninguna prueba y escribelos como comentario. Posteriormente, agrega los print que consideres necesarios para verificar que valores tiene b, c, d, e, f, g, h .

In [28]:
#Generamos el ndarray
a = np.arange(100)

# Chacamos algunas propiedades
print("El número de dimensiones de a es: {}".format(a.ndim))
print("Y su forma es {}".format(a.shape))
print("Y tiene {} elementos".format(a.size))

El número de dimensiones de a es: 1
Y su forma es (100,)
Y tiene 100 elementos


In [29]:
#Generamos algunos ndarrays a partir de a
b, c = a[:20], a[20:]
d, e = a[-1:-10:-1], a[10:11]
f = a[::-1]
g = a[a % 5 == 0]
h = f[[1, 15, 60]]

# Ahora trata de inferir que es lo que debe contener cada array b, c, d, e, f, g, h sin hacer ninguna prueba.
# 
# b = [0,1,2,3,4,5,6,...,19]
# c = [19,21,22,23,...99]
# d = []

In [31]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])